sonar.projectKey=ShaggyMission_Version-control-backend
sonar.organization=shaggymission

sonar.sources=src
sonar.exclusions=**/node_modules/**,**/.next/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info