name: Deploy to Railway

on:
  push:
    branches:
      - main  # Cambia esto si tu rama de producción es otra

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy with Railway
        run: railway up --service version-control-web
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
